import { View, Text } from "@react-pdf/renderer";
import { pdfStyles as s } from "./PdfStyles";

export function PdfFooter() {
  const now = new Date();
  const dateStr = new Intl.DateTimeFormat("en-IN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    timeZone: "Asia/Kolkata",
  }).format(now);

  return (
    <View style={s.footer} fixed>
      <Text style={s.footerText}>Generated by Ledge · {dateStr}</Text>
      <Text style={s.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}
